//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pMaker.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_VIEW_SELECTIONMODE           101
#define ID_VIEW_VIEWINGMODE             102
#define IDD_IVDIALOG_DIALOG             102
#define ID_HORIZ_BUTTON                 103
#define ID_VERT_BUTTON                  104
#define ID_TREES_SAVETREEPARAMETERS     105
#define IDR_MAINFRAME                   128
#define IDR_pMakerTYPE                  129
#define IDD_GET_INTEGER_DIALOG          130
#define IDD_GET_FLOAT_DIALOG            132
#define IDR_MENU1                       132
#define IDD_HOLE_DIALOG                 133
#define IDD_SEGMENT_DLG                 134
#define IDD_SHAPE_MARKER_DIALOG         135
#define IDD_GET_ONE_INTEGER_DLG         136
#define IDD_WHICH_BRANCH_DIALOG1        137
#define IDD_FRACTAL_TREE_DIALOG         138
#define IDD_GET_SCALES_DIALOG           139
#define IDD_DIALOG1                     140
#define IDD_DIALOG2                     141
#define IDD_GET_STRING_DIALOG           141
#define IDC_VIEWER                      998
#define IDC_LOAD                        1000
#define IDC_SAVE                        1001
#define IDC_EDIT2                       1001
#define IDC_CLEAR                       1002
#define IDC_EDIT3                       1002
#define IDC_LEFT_ABR                    1002
#define IDC_CHECK_CLOSED                1003
#define IDC_EDIT4                       1003
#define IDC_SPIN1                       1004
#define IDC_EDIT5                       1004
#define IDC_INFL_DIR                    1004
#define IDC_SPIN2                       1005
#define IDC_VERT_EXAG                   1005
#define IDC_EDIT6                       1005
#define IDC_RIGHT_ABR                   1005
#define IDC_INTEGER_EDIT                1006
#define IDC_DXF                         1006
#define IDC_LEFT_BRANCH                 1006
#define IDC_STATIC_UPPER                1007
#define IDC_LOAD_BG                     1007
#define IDC_EDIT8                       1007
#define IDC_STATIC_LOWER                1008
#define IDC_REVERSE                     1008
#define IDC_INTEGER_EDIT2               1009
#define IDC_DXF_OUT                     1009
#define IDC_CHECK_EXPONENTIAL           1009
#define IDC_SLIDER1                     1010
#define IDC_CHECK_SPIRAL                1010
#define IDC_SEC_SCALE                   1011
#define IDC_CHECK_LINEAR                1011
#define IDC_FLOAT_EDIT                  1012
#define IDC_CENT_SCALE                  1012
#define IDC_EDIT_OFFSET                 1013
#define IDC_CHECK_LEVEL_DETAILS         1013
#define IDC_THICKNESS                   1013
#define IDC_EDIT_SEGMENT                1014
#define IDC_EDIT_SPACING                1014
#define IDC_CHECK_INFLUENCE             1014
#define IDC_EDIT_SIDE                   1015
#define IDC_THICK_1                     1015
#define IDC_LTHICK_1                    1015
#define IDC_SEGMENT                     1016
#define IDC_BROWSE_BRANCH               1016
#define IDC_MARKER_SIZE                 1017
#define IDC_THICK_2                     1017
#define IDC_PREFIX                      1017
#define IDC_LTHICK_2                    1017
#define IDC_USE_THICKNESS               1018
#define IDC_THICK_3                     1019
#define IDC_LTHICK_3                    1019
#define IDC_RTHICK_1                    1020
#define IDC_THICK_4                     1021
#define IDC_LTHICK_4                    1021
#define IDC_RTHICK_2                    1022
#define IDC_THICK_5                     1023
#define IDC_LTHICK_5                    1023
#define IDC_RTHICK_3                    1024
#define IDC_SPIN_SIZE                   1025
#define IDC_THICK_6                     1025
#define IDC_LTHICK_6                    1025
#define IDC_SPIN_SEGMENT                1026
#define IDC_RTHICK_4                    1026
#define IDC_EDIT1                       1027
#define IDC_BROWSE_BRANCH2              1027
#define IDC_SPLINE_BUTTON               1028
#define IDC_THICK_7                     1028
#define IDC_LTHICK_7                    1028
#define IDC_RADIO_LEFT                  1029
#define IDC_PSCALE_1                    1029
#define IDC_LSCALE_1                    1029
#define IDC_RADIO_RIGHT                 1030
#define IDC_PSCALE_2                    1030
#define IDC_LSCALE_2                    1030
#define IDC_PSCALE_3                    1031
#define IDC_LSCALE_3                    1031
#define IDC_PSCALE_4                    1032
#define IDC_LSCALE_4                    1032
#define IDC_PSCALE_5                    1033
#define IDC_LSCALE_5                    1033
#define IDC_PSCALE_6                    1034
#define IDC_LSCALE_6                    1034
#define IDC_PSCALE_7                    1035
#define IDC_LSCALE_7                    1035
#define IDC_RSCALE_1                    1036
#define IDC_RSCALE_2                    1037
#define IDC_RSCALE_3                    1038
#define IDC_RSCALE_4                    1039
#define IDC_RSCALE_5                    1040
#define IDC_RSCALE_6                    1041
#define IDC_THICK_8                     1042
#define IDC_LTHICK_8                    1042
#define IDC_PSCALE_8                    1043
#define IDC_LSCALE_8                    1043
#define IDC_THICK_9                     1044
#define IDC_LTHICK_9                    1044
#define IDC_PSCALE_9                    1045
#define IDC_LSCALE_9                    1045
#define IDC_RSCALE_7                    1046
#define IDC_RSCALE_8                    1047
#define IDC_RSCALE_9                    1048
#define IDC_RTHICK_5                    1049
#define IDC_RTHICK_6                    1050
#define IDC_RTHICK_7                    1051
#define IDC_RTHICK_8                    1052
#define IDC_RTHICK_9                    1053
#define IDC_NUM_LEVELS                  1054
#define IDC_BROWSE_BRANCH3              1055
#define IDC_BUTTON1                     1056
#define IDC_BUTTON2                     1057
#define IDC_SAVE_FRACTALTREESPEC        1057
#define IDC_LROT_1                      1066
#define IDC_LROT_2                      1067
#define IDC_LROT_3                      1068
#define IDC_LROT_4                      1069
#define IDC_LROT_5                      1070
#define IDC_LROT_6                      1071
#define IDC_LROT_7                      1072
#define IDC_USE_ROTATION                1073
#define IDC_LROT_8                      1074
#define IDC_LROT_9                      1075
#define IDC_LINFL_1                     1076
#define IDC_LINFL_2                     1077
#define IDC_LINFL_3                     1078
#define IDC_LINFL_4                     1079
#define IDC_LINFL_5                     1080
#define IDC_LINFL_6                     1081
#define IDC_LINFL_7                     1082
#define IDC_USE_INFL                    1083
#define IDC_LINFL_8                     1084
#define IDC_LINFL_9                     1085
#define IDC_USE_PATH_SCALE              1086
#define IDC_RINFL_1                     1087
#define IDC_RINFL_2                     1088
#define IDC_RINFL_3                     1089
#define IDC_RINFL_4                     1090
#define IDC_RINFL_5                     1091
#define IDC_RINFL_6                     1092
#define IDC_RINFL_7                     1093
#define IDC_RROT_1                      1094
#define IDC_RINFL_8                     1095
#define IDC_RINFL_9                     1096
#define IDC_RROT_2                      1097
#define IDC_RROT_3                      1098
#define IDC_RROT_4                      1099
#define IDC_RROT_5                      1100
#define IDC_RROT_6                      1101
#define IDC_RROT_7                      1102
#define IDC_FACTOR_EDIT                 1103
#define IDC_RROT_8                      1104
#define IDC_RROT_9                      1105
#define ID_FILE_INFO                    32771
#define ID_FILE_CHANGELOFTSCALES        32772
#define ID_CHANGELOFTSCALES_CHAN        32773
#define ID_FILE_CHANGE_LOFT_SCALE       32774
#define ID_TREES_FLATTENALLLEVELS       32775
#define ID_FLATTEN_ALL_LEVELS           32776
#define ID_TREES_LOADTREESPECFROMFILE   32777
#define ID_FILE_EXTRUDEBETWEEN2SHAPES   32778
#define ID_FILE_LOADMULTIPLECROSS       32779
#define ID_TREES_SAVEFRACTALTREESPEC    32780
#define ID_VIEW_PICEDIT                 32795
#define ID_FILE_IMPORT                  32817
#define ID_FILE_RELOAD                  32818
#define ID_X_SEC_BUTTON                 32823
#define ID_TWIST_BUTTON                 32824
#define ID_VSCALE_BUTTON                32825
#define ID_ADD_BACKGROUND               32826
#define ID_DELETE_BACKGROUND            32827
#define ID_HSCALE_BUTTON                32828
#define ID_FILE_DXFTOIV                 32829
#define ID_SAVELOFT                     32830
#define ID_REMOVELOFT                   32831
#define ID_THREE_D_BUTTON               32832
#define ID_SAVE_CONSTRUCTION_DATA       32833
#define ID_LOAD_CONSTRUCTION_DATA       32834
#define ID_FLATTEN                      32835
#define ID_FLATTEN_POLYLINE             32836
#define ID_EDIT_BEGIN_END               32837
#define ID_EDIT_MULTIPLES               32838
#define ID_EDIT_TRANSFORM_BOX_ON        32839
#define ID_EDIT_TRANSFORM_BOX_OFF       32840
#define ID_FILE_SAVE_MULTIIPLES         32841
#define ID_EDIT_OFFSET                  32842
#define ID_EDIT_ADD_HOLES               32843
#define ID_EDIT_CLIPPLANE               32844
#define ID_EDIT_CLIPPLANEOFF            32845
#define ID_ANTISQUISH                   32846
#define ID_FILE_FLATTENIMPORTEDCOORDS   32847
#define ID_FLATTEN_TWO                  32848
#define ID_REVERSE                      32849
#define ID_VERT_EQ_HORIZ                32850
#define ID_ADD_BACKGND_SOLID            32851
#define ID_SEARCH_BACKGROUND            32852
#define ID_USE_SEGMENT_DIALOG           32853
#define ID_REMOVE_TRANSFORM             32854
#define ID_USE_MARKERS                  32855
#define ID_EDIT_ORIENT_TO_REFERENCE_LINE 32856
#define ID_TREES_TEST_TREE              32857
#define ID_TREES_TEST2                  32858
#define ID_TREES_SAVEEXTRUSIONANDCENTERLINE 32859

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
